### ISSUE TITLE
Test failures on osx since 0.8.x

### ISSUE THREAD

**Issue by h-vetinari** [awslabs/aws-c-mqtt#257] opened 2023-01-26 22:29 UTC
Hey all

We're packaging aws-sdk-cpp and a couple of aws-c-* components for conda-forge (some packages like pyarrow produce bindings, so we want/need the libs).

Since aws-c-mqtt 0.8, there's been a test failure in the test suite (on osx-64, not on linux/win) about 1-2 tests either failing or segfaulting:
```
mqtt5_client_reconnect_failure_backoff
mqtt5_client_reconnect_backoff_sufficient_reset 
```

I checked the test [logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/647880/logs/47) today (from this [PR](https://github.com/conda-forge/aws-c-mqtt-feedstock/pull/105#pullrequestreview-1271853144)), and the failure looks like:
```
***FAILURE*** Expected success at s_verify_reconnection_exponential_backoff_timestamps(&test_context); got return value -1 with last error 0x0000
[s_mqtt5_client_reconnect_failure_backoff_fn():$SRC_DIR/tests/v5/mqtt5_client_tests.c@#1499]
```
The one line that caught my attention was:
```
[INFO] [2023-01-26T13:47:18Z] [0000700008158000] [mqtt5-client] - id=0x7fc11fd07e90: channel tore down with error code 5150(libaws-c-mqtt: AWS_ERROR_MQTT5_CONNACK_CONNECTION_REFUSED, Remote endpoint rejected the CONNECT attempt by returning an unsuccessful CONNACK)
```
which appeared several itmes before that, but I have no idea if that's relevant.

The segfaulting `mqtt5_client_reconnect_backoff_sufficient_reset` has the same error appear as well:
```
[INFO] [2023-01-26T13:48:11Z] [000070000ad6c000] [mqtt5-client] - id=0x7fcde7d06b50: channel tore down with error code 5150(libaws-c-mqtt: AWS_ERROR_MQTT5_CONNACK_CONNECTION_REFUSED, Remote endpoint rejected the CONNECT attempt by returning an unsuccessful CONNACK)
[...]
[TRACE] [2023-01-26T13:48:11Z] [000070000abe3000] [event-loop] - id=0x7fcde7c0a9d0: waiting for a maximum of 0s 0ns
***FAILURE*** Expected success at s_verify_reconnection_after_success_used_backoff(&test_context, RECONNECT_TEST_MIN_BACKOFF); got return value -1 with last error 0x0000
 [s_mqtt5_client_reconnect_backoff_sufficient_reset_fn():$SRC_DIR/tests/v5/mqtt5_client_tests.c@#1854]
<end of output>
Test time =  29.02 sec
----------------------------------------------------------
Test Failed.
"mqtt5_client_reconnect_backoff_sufficient_reset" end time: Jan 26 13:48 UTC
"mqtt5_client_reconnect_backoff_sufficient_reset" time elapsed: 00:00:29
----------------------------------------------------------
```

Could someone help us out with this? E.g. it would already be fine to know that we can skip those two tests, e.g. because they cannot be expected to pass in CI, etc.

PS. I wanted to paste the full trace of `mqtt5_client_reconnect_failure_backoff` but got an error that it's too long. It's there under the above [link](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/647880/logs/47) for a month now (because azure cleans up the CI results for PR runs after that time).

**Comment by TwistedTwigleg** [comment] 2023-01-27 20:49
Thank you for creating this issue and providing logs!

I am looking into this issue currently. A few questions:
* Does this issue only occur in CI? Have you been able to reproduce the issue locally?
* Does this issue occur every time the test suite is run? Does it just occur sometimes?
* Just to confirm: it is only these two tests that fail?
* Do both tests fail every time?

We test on Mac computers during development and we run tests against Mac in CI, so it is a bit strange that it is failing here on a Mac. I have just tested running the tests locally on my Mac and it passes successfully.

I did a quick look at the logs after running the test locally, and have found several occurrences of `channel tore down with error code 5150(libaws-c-mqtt: AWS_ERROR_MQTT5_CONNACK_CONNECTION_REFUSED, Remote endpoint rejected the CONNECT attempt by returning an unsuccessful CONNACK)`, so I do not think that is the issue necessarily, but I have not ruled it out yet either.

I am going to run the tests again locally and compare the logs I get with the logs provided in a 1:1 fashion and see what differences there are to see if that provides insight into what is going on. I may be able to spot the differences and that could help me determine what is going on and how to fix it.

____________

Looking at the two tests that are failing, there is a few things in common across both of them:
* Both tests are reconnect tests
* Both tests fail checking timestamps and whether they are within a certain expected range.
  * `mqtt5_client_reconnect_backoff_sufficient_reset` is failing on the `s_verify_reconnection_after_success_used_backoff` function based on the log.
  * `mqtt5_client_reconnect_failure_backoff` is failing on the `s_verify_reconnection_exponential_backoff_timestamps` function based on the log.

I'm wondering if what is happening is the difference between the expected time and the actual time is just slightly greater than 10% in your CI, and so it fails. For example, [the code in](https://github.com/awslabs/aws-c-mqtt/blob/main/tests/v5/mqtt5_client_tests.c#L1397) `s_verify_reconnection_exponential_backoff_timestamps` has a tolerance of `0.1` difference between the expected backoff time and the actual backoff time observed.

I am wondering if extending that difference to something like `0.15` would fix the issue, as it seems like it may be *just* on the edge of being able to complete, assuming it is not failing both tests every time.

Can you compile from source? If so, can you see if modifying the following spots allows helps?
* https://github.com/awslabs/aws-c-mqtt/blob/main/tests/v5/mqtt5_client_tests.c#L1397 -> Change `.1` to `.15` in `if (!s_is_within_percentage_of(expected_backoff, time_diff, .1)) {`
* https://github.com/awslabs/aws-c-mqtt/blob/main/tests/v5/mqtt5_client_tests.c#L1615 -> Change `.1` to `.15` in `if (!s_is_within_percentage_of(expected_reconnect_delay_ms, post_success_reconnect_time_ms, .1)) {`

If it would help, I can make a testing branch with these changes - just let me know and I will make the adjustments.

__________

As far as the segfault goes - I am unsure on why that is occurring. I am going to keep looking at the logs to see what I can find, but I did notice in each test you have the following:

For `mqtt5_client_reconnect_failure_backoff`:
~~~
2023-01-26T13:49:35.8608350Z ***FAILURE*** Expected success at s_verify_reconnection_exponential_backoff_timestamps(&test_context); got return value -1 with last error 0x0000
2023-01-26T13:49:35.8609430Z  [s_mqtt5_client_reconnect_failure_backoff_fn():$SRC_DIR/tests/v5/mqtt5_client_tests.c@#1499]
~~~

For `s_mqtt5_client_reconnect_backoff_sufficient_reset_fn`:
~~~
2023-01-26T13:49:38.2561660Z ***FAILURE*** Expected success at s_verify_reconnection_after_success_used_backoff(&test_context, RECONNECT_TEST_MIN_BACKOFF); got return value -1 with last error 0x0000
2023-01-26T13:49:38.2562750Z  [s_mqtt5_client_reconnect_backoff_sufficient_reset_fn():$SRC_DIR/tests/v5/mqtt5_client_tests.c@#1854]
~~~

Which to me indicates that potentially the segfault may just be due to the test failing, but again, I will look into it further to see if I can better figure out what is going on.

**Comment by h-vetinari** [comment] 2023-01-27 22:26
Hey, thanks for the quick response!

> I am looking into this issue currently. A few questions:
>  * Does this issue only occur in CI? Have you been able to reproduce the issue locally?

Always in CI, haven't tried locally (no mac)

> * Does this issue occur every time the test suite is run? Does it just occur sometimes?

Occurred always

> * Just to confirm: it is only these two tests that fail?

From what I was able to see, yes.
> * Do both tests fail every time?

I've seen runs where only one of the two failed.



> I'm wondering if what is happening is the difference between the expected time and the actual time is just slightly greater than 10% in your CI, and so it fails. For example, [the code in](https://github.com/awslabs/aws-c-mqtt/blob/main/tests/v5/mqtt5_client_tests.c#L1397) `s_verify_reconnection_exponential_backoff_timestamps` has a tolerance of `0.1` difference between the expected backoff time and the actual backoff time observed.

This sounds like an extremely likely scenario. Public CI like we use for conda-forge is much less powerful than other agents, and timing assumptions in tests are always tricky.

> Can you compile from source? If so, can you see if modifying the following spots allows helps?

I can and I [did](https://github.com/conda-forge/aws-c-mqtt-feedstock/pull/105), though I went from `.1` -> `.3` directly (I actually want to get rid of the failing tests, not just have them slightly less flaky), and the tests passed 🥳 

Maybe there's a middle-ground somewhere that works for us both? I'd like to avoid carrying a patch for our infra, though this might work if the tests in question don't change that often...

**Comment by TwistedTwigleg** [comment] 2023-01-27 22:48
Thank you for the reply and answering the questions, very much appreciated!

________

Based on that it works with `.3` instead of `.1` and the public CI is less powerful than other agents, it seems likely the issue is timing in responses and that is causing the problem. It seems to be the most likely scenario and from what I saw in the logs, nothing really jumped out when I was doing a 1:1 other than there was a bit more delay in the server's response (but not huge though...).

> Maybe there's a middle-ground somewhere that works for us both? I'd like to avoid carrying a patch for our infra, though this might work if the tests in question don't change that often...

That totally makes sense and I agree that it is ideal if we find a way that helps fix the issue while keeping the test as expected. I am going to look into seeing if I can find a way to adjust how the test tracks time so that, on slower request/response scenarios, the test does not fail.

**Comment by h-vetinari** [comment] 2023-01-27 23:38
> That totally makes sense and I agree that it is ideal if we find a way that helps fix the issue while keeping the test as expected. I am going to look into seeing if I can find a way to adjust how the test tracks time so that, on slower request/response scenarios, the test does not fail.

What I meant was a more pragmatic: "what's the highest value instead of `.1` you could live with?". You proposed `0.15` (50% increase), which I feel is too low (might get a slow, congested agent, etc.). I proposed `0.3` (200% increase), and assumed that that might be too much for you, but happy to find something in between if we can.

**Comment by TwistedTwigleg** [comment] 2023-02-02 14:20
Sorry about the delay in replying, things have gotten a bit busy and then I was out for a bit for personal reasons.

> What I meant was a more pragmatic: "what's the highest value instead of .1 you could live with?". You proposed 0.15 (50% increase), which I feel is too low (might get a slow, congested agent, etc.). I proposed 0.3 (200% increase), and assumed that that might be too much for you, but happy to find something in between if we can.

That is an option too, we could just increase the value to something higher and try to find a happy middle ground between where we are currently and what works for congested devices. That is certainly the easiest solution to implement, we'd just need to find a value that is close enough that we feel comfortable that it still checks what we are looking for while also being wide enough for slower machines.

Ideally what I want to find is a solution to detect slower scenarios and adjust the test accordingly in a minimal way, so the intent of the test and what it is testing is still intact for faster machines (so we can confirm accuracy) without causing crashes and problems on slower machines. That is the ideal, but finding a way to get there and determine the "speed" of the machine is the harder part and requires careful thought on how we want to go about it. I am still thinking about how to best do this and hope to have a solution in the near future.

**Comment by TwistedTwigleg** [comment] 2023-02-03 23:10
Thank you for your patience - the fix has been implemented. Short term, we just increased the threshold from `0.1` to `0.3` and later we'll find a different solution once we have more time to dedicate to it. The fix is merged and will be in the next release 🙂

**Closed** 2023-02-03 23:10 UTC
Labels: bug

**Comment by h-vetinari** [comment] 2023-02-04 03:09
Great thanks a lot!
